<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FeatherWeather</AssemblyName>
    <RootNamespace>FeatherWeather</RootNamespace>
    <StartupObject>FeatherWeather.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>false</PublishSingleFile>
    <DebugType>embedded</DebugType>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
    <DebugSymbols>false</DebugSymbols>
    <TieredCompilation>true</TieredCompilation>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>
</Project>
