//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatherWeather.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeatherWeather.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feather Weather.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved at {0:t} · updating in the background.
        /// </summary>
        public static string CachedUpdateFormat {
            get {
                return ResourceManager.GetString("CachedUpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a city.
        /// </summary>
        public static string CityInputToolTip {
            get {
                return ResourceManager.GetString("CityInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City not found..
        /// </summary>
        public static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data: Open-Meteo.
        /// </summary>
        public static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to London.
        /// </summary>
        public static string DefaultCity {
            get {
                return ResourceManager.GetString("DefaultCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string DefaultDisplayCity {
            get {
                return ResourceManager.GetString("DefaultDisplayCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weather service returned an empty response..
        /// </summary>
        public static string EmptyWeatherResponse {
            get {
                return ResourceManager.GetString("EmptyWeatherResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels like {0:0}°.
        /// </summary>
        public static string FeelsLikeFormat {
            get {
                return ResourceManager.GetString("FeelsLikeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels like: --°.
        /// </summary>
        public static string FeelsLikePlaceholder {
            get {
                return ResourceManager.GetString("FeelsLikePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching forecast.
        /// </summary>
        public static string FetchingForecast {
            get {
                return ResourceManager.GetString("FetchingForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next hours.
        /// </summary>
        public static string HourlyForecastHeading {
            get {
                return ResourceManager.GetString("HourlyForecastHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        public static string HumidityFormat {
            get {
                return ResourceManager.GetString("HumidityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string HumidityLabel {
            get {
                return ResourceManager.GetString("HumidityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --%.
        /// </summary>
        public static string HumidityPlaceholder {
            get {
                return ResourceManager.GetString("HumidityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string LanguageArabic {
            get {
                return ResourceManager.GetString("LanguageArabic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose the application language..
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        public static string LanguageDutch {
            get {
                return ResourceManager.GetString("LanguageDutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string LanguageFrench {
            get {
                return ResourceManager.GetString("LanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string LanguageGerman {
            get {
                return ResourceManager.GetString("LanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        public static string LanguageItalian {
            get {
                return ResourceManager.GetString("LanguageItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        public static string LanguagePolish {
            get {
                return ResourceManager.GetString("LanguagePolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string LanguagePortuguese {
            get {
                return ResourceManager.GetString("LanguagePortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string LanguageSpanish {
            get {
                return ResourceManager.GetString("LanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Українська.
        /// </summary>
        public static string LanguageUkrainian {
            get {
                return ResourceManager.GetString("LanguageUkrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        public static string LocationFormat {
            get {
                return ResourceManager.GetString("LocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavigationSettingsToolTip {
            get {
                return ResourceManager.GetString("NavigationSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string NavigationWeatherToolTip {
            get {
                return ResourceManager.GetString("NavigationWeatherToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} mmHg.
        /// </summary>
        public static string PressureFormat {
            get {
                return ResourceManager.GetString("PressureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string PressureLabel {
            get {
                return ResourceManager.GetString("PressureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- mmHg.
        /// </summary>
        public static string PressurePlaceholder {
            get {
                return ResourceManager.GetString("PressurePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh weather.
        /// </summary>
        public static string RefreshWeatherToolTip {
            get {
                return ResourceManager.GetString("RefreshWeatherToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        public static string SevenDayForecastHeading {
            get {
                return ResourceManager.GetString("SevenDayForecastHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd, d MMM.
        /// </summary>
        public static string ShortDayFormat {
            get {
                return ResourceManager.GetString("ShortDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        public static string ShortTimeFormat {
            get {
                return ResourceManager.GetString("ShortTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}°.
        /// </summary>
        public static string TemperatureFormat {
            get {
                return ResourceManager.GetString("TemperatureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --°.
        /// </summary>
        public static string TemperaturePlaceholder {
            get {
                return ResourceManager.GetString("TemperaturePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}°  {1:0}°.
        /// </summary>
        public static string TemperatureRangeFormat {
            get {
                return ResourceManager.GetString("TemperatureRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an appearance or follow Windows settings..
        /// </summary>
        public static string ThemeDescription {
            get {
                return ResourceManager.GetString("ThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated at {0:t}.
        /// </summary>
        public static string UpdatedFormat {
            get {
                return ResourceManager.GetString("UpdatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update: {0}.
        /// </summary>
        public static string UpdateFailedFormat {
            get {
                return ResourceManager.GetString("UpdateFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating….
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear sky.
        /// </summary>
        public static string WeatherClearSky {
            get {
                return ResourceManager.GetString("WeatherClearSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle.
        /// </summary>
        public static string WeatherDrizzle {
            get {
                return ResourceManager.GetString("WeatherDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        public static string WeatherFog {
            get {
                return ResourceManager.GetString("WeatherFog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing drizzle.
        /// </summary>
        public static string WeatherFreezingDrizzle {
            get {
                return ResourceManager.GetString("WeatherFreezingDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing rain.
        /// </summary>
        public static string WeatherFreezingRain {
            get {
                return ResourceManager.GetString("WeatherFreezingRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☀.
        /// </summary>
        public static string WeatherGlyphClear {
            get {
                return ResourceManager.GetString("WeatherGlyphClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☁.
        /// </summary>
        public static string WeatherGlyphCloudy {
            get {
                return ResourceManager.GetString("WeatherGlyphCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☂.
        /// </summary>
        public static string WeatherGlyphDrizzle {
            get {
                return ResourceManager.GetString("WeatherGlyphDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≋.
        /// </summary>
        public static string WeatherGlyphFog {
            get {
                return ResourceManager.GetString("WeatherGlyphFog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⛅.
        /// </summary>
        public static string WeatherGlyphPartlyCloudy {
            get {
                return ResourceManager.GetString("WeatherGlyphPartlyCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☔.
        /// </summary>
        public static string WeatherGlyphRain {
            get {
                return ResourceManager.GetString("WeatherGlyphRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❄.
        /// </summary>
        public static string WeatherGlyphSnow {
            get {
                return ResourceManager.GetString("WeatherGlyphSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ϟ.
        /// </summary>
        public static string WeatherGlyphThunderstorm {
            get {
                return ResourceManager.GetString("WeatherGlyphThunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainly clear.
        /// </summary>
        public static string WeatherMainlyClear {
            get {
                return ResourceManager.GetString("WeatherMainlyClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        public static string WeatherOvercast {
            get {
                return ResourceManager.GetString("WeatherOvercast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly cloudy.
        /// </summary>
        public static string WeatherPartlyCloudy {
            get {
                return ResourceManager.GetString("WeatherPartlyCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string WeatherRain {
            get {
                return ResourceManager.GetString("WeatherRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain showers.
        /// </summary>
        public static string WeatherRainShowers {
            get {
                return ResourceManager.GetString("WeatherRainShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string WeatherSnow {
            get {
                return ResourceManager.GetString("WeatherSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow showers.
        /// </summary>
        public static string WeatherSnowShowers {
            get {
                return ResourceManager.GetString("WeatherSnowShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm.
        /// </summary>
        public static string WeatherThunderstorm {
            get {
                return ResourceManager.GetString("WeatherThunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with hail.
        /// </summary>
        public static string WeatherThunderstormWithHail {
            get {
                return ResourceManager.GetString("WeatherThunderstormWithHail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string WeatherUnknown {
            get {
                return ResourceManager.GetString("WeatherUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string WindLabel {
            get {
                return ResourceManager.GetString("WindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- m/s.
        /// </summary>
        public static string WindPlaceholder {
            get {
                return ResourceManager.GetString("WindPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.#} m/s.
        /// </summary>
        public static string WindSpeedFormat {
            get {
                return ResourceManager.GetString("WindSpeedFormat", resourceCulture);
            }
        }
    }
}
